SELECT * FROM (SELECT City, LENGTH(City) AS CityLength FROM STATION ORDER BY CityLength,City LIMIT 1) AS SHORTEST
UNION
SELECT * FROM (SELECT City, LENGTH(City) AS CityLength FROM STATION ORDER BY CityLength DESC,City LIMIT 1) AS LONGEST
